### ISSUE TITLE
i couldn't connect to the service api - youtube

### ISSUE THREAD

**Issue by ogohogo** [wukko/cobalt#372]
**bug description**
Upon attempting to download YouTube link I get error "i couldn't connect to the service api. maybe it's down, or cobalt got blocked.". This has been tested with 3 different instances in 3 different locations
InnertubeError: Request to https://www.youtube.com/youtubei/vtrue/player?key=x&prettyPrint=false&alt=json failed with status 400

**reproduction steps**
steps to reproduce the behavior:
1. Attempt to download YouTube video
2. Get error described in description

**screenshots**
-

**links**
-

**platform**
- OS Local machine runs on Windows 11, server on Ubuntu 22.10
- browser - Brave 
- version - Version 1.63.162 Chromium: 122.0.6261.69 (Official Build)  (64-bit)

**additional context**
Only Hetzner instances located in Germany and Finland has been tested

**Comment by ogohogo** [comment]
I've discovered this is related to youtubei.js.

Go to node_modules/youtubei.js/dist/src/core

In Session.js change `v${ytcfg[0][0][6]}` to `v1` to fix it.

**Comment by nikunjmishra1998** [comment]
@ogohogo I was recieved same error before a day ago. but after I upgrade youtubei.js to 9.1.0,  I received download usrl in /api/json route. the issue is when I access the same url, I received 0 byte mp3 file.


I am using node 20.11.1
WSL Ubuntu 22.04 on my local system

Curl for localhost

curl --location 'http://localhost:9000/api/json' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'sec-ch-ua: "Google Chrome";v="122", "Not;A=Brand";v="8", "Chromium";v="122"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "Windows"' \
--header 'sec-fetch-dest: empty' \
--header 'sec-fetch-mode: cors' \
--header 'sec-fetch-site: cross-site' \
--data '{
    "url": "https://www.youtube.com/watch?v=r0JvNvgBLWo",
    "aFormat": "mp4",
    "dubLang": false,
    "isAudioOnly": true,
    "isNoTTWatermark": true
  }'

**Comment by wukko** [comment]
@nikunjmishra1998
1. user agent isn't necessary
2. youtube rate limited your server
3. we already released an update for docker package that fixes the youtubei.js issue

**Comment by nikunjmishra1998** [comment]
@wukko, 
1) I removed user agent.
2) I have started it cobalt API on my local system first time.
3) Already pulled with the latest code from the your git repo.

fyi I am not executing API with docker, just running with normal npm. But reciving 0 byte file

**Comment by ogohogo** [comment]
> 3\. lready released an update for docker package that fixes the youtubei.js issue

Rotate your ipv6 (if you have one) to fix this issue
If you don't, then you need to get a new server

**Comment by lostdusty** [comment]
> @wukko,
> 
> 1. I removed user agent.
> 2. I have started it cobalt API on my local system first time.
> 3. Already pulled with the latest code from the your git repo.
> 
> fyi I am not executing API with docker, just running with normal npm. But still receiving 0 byte file

Try using docker then..?

**Comment by nikunjmishra1998** [comment]
@wukko 
> Try using docker then..?

I used docker to host my own instance for API but API gaves me below response

{
    "status": "error",
    "text": "i couldn't connect to the service api. maybe it's down, or cobalt got blocked. try again, but if error persists, check the <a class=\"text-backdrop link\" href=\"https://status.cobalt.tools/\" target=\"_blank\">status page</a> or <a class=\"text-backdrop link\" href=\"https://github.com/wukko/cobalt\" target=\"_blank\">create an issue on github</a>..",
    "critical": true
}

**Comment by dumbmoron** [comment]
in that case your IP is most likely blocked by youtube
